### ISSUE TITLE
Production Build Error

### ISSUE THREAD

**Issue by JosephLuns** [Wykks/ngx-mapbox-gl#185] opened 2019-09-16 01:39 UTC
I have angular 8 project and installed 3.3.1 and it works great in local build
but when I try to build for production, I am getting this error

ERROR in scripts.971814be3712be47bd5f.js from Terser
Unexpected token: punc (.) [node_modules/mapbox-gl/dist/mapbox-gl.css:1,0][scripts.971814be3712be47bd5f.js:19907,1]

any ideas?

**Comment by abheyshah** [comment] 2019-09-21 14:17
try this `ng build --prod --named-chunks --verbose --build-optimizer=false --source-map `
it might help you find the issue.

**Comment by dmytro-gokun** [comment] 2019-10-11 19:05
@JosephLuns Do you still have a problem? If yes, please build & share a minimal reproduction project, so someone can step up and help.

**Comment by dmytro-gokun** [comment] 2019-10-25 19:26
Closing this because of no reproduction information was provided. If you still have an issue/question, feel free to open a new issue and provide more details.

**Closed by dmytro-gokun** 2019-10-25 19:26 UTC
Labels: need more info
