### ISSUE TITLE
Production build errors CLI ~7.1.0

### ISSUE THREAD

**Issue by dimitrilahaye** [Wykks/ngx-mapbox-gl#116] opened 2019-03-12 12:10 UTC
Hello there!
I'm using @angular/cli ~7.1.0 and when I build in prod environnement, I have this error:

`Module not found: Error: Can't resolve 'ngx-mapbox-gl/lib/control/geocoder-control.directive'`

There, my package json:

```js
{
  "name": "immo",
  "version": "0.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --open --port 4201",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "build:demo": "ng build --prod --configuration=demo",
    "start:demo": "npm run build:demo && ng serve --prod --port 4201 --configuration=demo"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^0.11.4",
    "@angular/animations": "~7.1.0",
    "@angular/cdk": "~7.1.0",
    "@angular/cli": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@angular/material": "~7.1.1",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@mapbox/mapbox-gl-geocoder": "^3.1.4",
    "@ng-select/ng-select": "^2.16.2",
    "@types/lodash": "^4.14.123",
    "@types/mapbox": "^1.6.38",
    "@types/mapbox-gl": "^0.49.1",
    "mapbox-gl": "^0.51.0",
    "@types/node": "~8.9.4",
    "angular2-multiselect-dropdown": "^4.2.1",
    "core-js": "^2.5.4",
    "geojson-filter": "^0.1.4",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "ng2-file-upload": "^1.3.0",
    "ngx-mapbox-gl": "^2.0.0",
    "ngx-numeral": "0.0.1-beta.0",
    "node-sass": "^4.11.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.2",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}
```
There the command we launch to build in "demo" mode (prod env.)

```shell
npm install --production
npm run build:demo
```
There the simple code in my html template to call the geocoder directive:

```html
      <mgl-control
        mglGeocoder
        [position]="'top-right'"
        [accessToken]="settings.mapbox_public_token"
        [flyTo]="false"
        (result)="goToGeocoderResult($event)"
      ></mgl-control>
```
Obviously, it works in dev mode.

Have you got some ideas for me?

**Comment by Wykks** [comment] 2019-03-17 00:12
Hi!

Have you checked your import statements ? Sometimes IDEs are not doing a good job. 
There's only one entry point, eg `import { ... } from 'ngx-mapbox-gl'`;

**Comment by dmytro-gokun** [comment] 2019-10-12 06:36
@dimitrilahaye Is this issue still relevant?

**Comment by dmytro-gokun** [comment] 2019-10-25 19:28
Closing this because of no reproduction information was provided. If you still have an issue/question, feel free to open a new issue and provide more details.

**Closed by dmytro-gokun** 2019-10-25 19:28 UTC
Labels: need more info
