### ISSUE TITLE
ivy breaks mgl-control

### ISSUE THREAD

**Issue by abheyshah** [Wykks/ngx-mapbox-gl#182] opened 2019-08-23 15:27 UTC
When i enable ivy, mgl-control (mglGeocoder) fails on instantiation without it it works fine.

**Comment by jrrembert** [comment] 2019-12-13 15:35
Also seeing this in Angular 8.2.14 (both with and without Ivy, all possible directives).

Will try to create a small reproducible example this weekend.

**Comment by dmytro-gokun** [comment] 2019-12-13 16:33
@jrrembert There is a geocoder example on demo site: https://wykks.github.io/ngx-mapbox-gl/demo/mapbox-gl-geocoder which is built using Angular 8.2.14. It appears to work just fine. Plz compare your code to the demo's code. 

In any case, the reproduction is really welcome.

**Comment by dmytro-gokun** [comment] 2020-07-24 08:31
I'm closing this because of no answer. If someone else experiences this issue with latest version, plz open a new issue and attach a reproduction

**Closed by dmytro-gokun** 2020-07-24 08:31 UTC
