### ISSUE TITLE
mgl-layer in *ngFor produces multiple errors

### ISSUE THREAD

**Issue by silviokennecke** [Wykks/ngx-mapbox-gl#88] opened 2018-12-23 23:14 UTC
Hello, I've got some troubles defining layers in a loop.
The data defining the layers changes very frequently.

For better explanaitions this is the code:
``` typescript
@Input() minPlaneSpeed = 10;
@Input() planes: Target[] = [];
```
``` html
<ng-container *ngFor="let plane of planes">
    <mgl-layer
        *ngIf="plane.speed >= minPlaneSpeed"
        [id]="'plane-' + plane.id"
        ...
    ></mgl-layer>
</ng-container>
```

When I update `this.planes`, I get a error that a layer with that id already exists.
``` typescript
// old value
this.planes = [
    {
        id: 'D-XXXX',
        speed: 39
    }
];

// new value
this.planes = [
    {
        id: 'D-XXXX',
        speed: 35
    }
];
```
This change gives me the following errors:
```
Error: Layer with id "plane-D-XXXX" already exists on this map    mapbox-gl.js:29
    at i.addLayer (mapbox-gl.js:33)
    at r.addLayer (mapbox-gl.js:33)
    at ngx-mapbox-gl.js:322
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:3779)
    at MapService.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.MapService.addLayer (ngx-mapbox-gl.js:313)
    at LayerComponent.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.LayerComponent.init (ngx-mapbox-gl.js:1766)
    at SafeSubscriber._next (ngx-mapbox-gl.js:1691)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:195)
```
```
Uncaught Error: There is already a source with this ID    zone.js:192
    at i.addSource (mapbox-gl.js:33)
    at i.addLayer (mapbox-gl.js:33)
    at r.addLayer (mapbox-gl.js:33)
    at ngx-mapbox-gl.js:322
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:3779)
    at MapService.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.MapService.addLayer (ngx-mapbox-gl.js:313)
    at LayerComponent.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.LayerComponent.init (ngx-mapbox-gl.js:1766)
    at SafeSubscriber._next (ngx-mapbox-gl.js:1691)
```

After another change I get the following errors:
```
Error: The layer 'plane-D-XXXX' does not exist in the map's style and cannot be removed.    mapbox-gl.js:29
    at i.removeLayer (mapbox-gl.js:33)
    at r.removeLayer (mapbox-gl.js:33)
    at MapService.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.MapService.removeLayers (ngx-mapbox-gl.js:866)
    at ngx-mapbox-gl.js:816
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:3779)
    at MapService.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.MapService.applyChanges (ngx-mapbox-gl.js:815)
    at ngx-mapbox-gl.js:845
    at SafeSubscriber.schedulerFn [as _next] (core.js:3563)
```
```
ERROR Error: There is already a source with this ID    core.js:1673
    at i.addSource (mapbox-gl.js:33)
    at i.addLayer (mapbox-gl.js:33)
    at r.addLayer (mapbox-gl.js:33)
    at ngx-mapbox-gl.js:322
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:3779)
    at MapService.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.MapService.addLayer (ngx-mapbox-gl.js:313)
    at LayerComponent.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.LayerComponent.init (ngx-mapbox-gl.js:1766)
    at SafeSubscriber._next (ngx-mapbox-gl.js:1691)
```

On every following change I get another error:
```
ERROR Error: There is already a source with this ID    core.js:1673
    at i.addSource (mapbox-gl.js:33)
    at i.addLayer (mapbox-gl.js:33)
    at r.addLayer (mapbox-gl.js:33)
    at ngx-mapbox-gl.js:322
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:3779)
    at MapService.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.MapService.addLayer (ngx-mapbox-gl.js:313)
    at LayerComponent.push../node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js.LayerComponent.init (ngx-mapbox-gl.js:1766)
    at SafeSubscriber._next (ngx-mapbox-gl.js:1691)
```

During debugging I found out that the layer should be removed `MapService.removeLayer()`, then the new one is added `MapService.addLayer()` and then `MapService.applyChanges()` is called. So when the layer is added the old one isn't removed at that point.

**Comment by silviokennecke** [comment] 2018-12-25 00:03
The same problem occurs if you remove a layer and add it again later.
``` typescript
// current value
this.planes = [
    {
        id: 'D-XXXX'
    }
];

// 1st value change
this.planes = [];

// 2nd value change
this.planes = [
    {
        id: 'D-XXXX'
    }
];
```

**Comment by Wykks** [comment] 2018-12-26 12:40
That's interesting, do you use ngZone noop implementation?

Can you reproduce the issue in stackblitz ?

**Comment by silviokennecke** [comment] 2018-12-27 18:50
I don't think so.

I created a stackbliz example here: https://stackblitz.com/edit/ngx-mapbox-gl-playground-n9qddo

**Comment by sroettering** [comment] 2019-01-02 07:51
Had the same error. I had to use a `trackBy` for the `*ngFor`.

**Comment by silviokennecke** [comment] 2019-01-02 09:04
Yes, the second scenario is working now. Would be great if can find a solution the first scenario, because it's the bigger issue. I get data updates very often (including removed objects and added again in a later data update).

**Comment by sroettering** [comment] 2019-01-02 09:20
Working first example: https://stackblitz.com/edit/ngx-mapbox-gl-playground-1x7wwc

I agree, however, that your original first example should be working with a trackBy function. It seems, that the source is not removed correctly.

**Comment by Wykks** [comment] 2019-01-02 11:24
Okay I see, I should add something to handle ngFor without trackBy. Since I use trackBy as soon as I can, I often forgot how ngFor without trackBy is so inefficient.
ngFor remove and re-add everything when there's no trackBy, in the same browser turn. Since mgx-mapbox-gl only actually remove the layer at the end of the turn, it doesn't work properly.
The good news is that I should be able to avoid the call to removeLayer/addLayer in this case. But it's still not great, and since layers must have an id, there's no reason to not use trackBy.
I'll add the fix, and a warning there :)

Not sure what's going on in the example where you embed the source in the layer. It's a mapbox-gl feature, ngx-mapbox-gl doesn't do anything special here. Probably a bug in mapbox-gl itself.

**Comment by behuda** [comment] 2019-03-03 10:33
`The good news is that I should be able to avoid the call to removeLayer/addLayer in this case.`
just curious how?
can u update the layer.component.ts or if there is commit regarding this.

**Comment by vamcs** [comment] 2019-06-12 06:27
I also ran into this and notice if I string-interpolate the id attribute instead of property-bind it this would work too.

**Comment by salmoro** [comment] 2019-12-01 20:33
@vamcs Care to elaborate or share an example?

**Comment by salmoro** [comment] 2019-12-01 20:40
@Wykks `trackBy` seems to help in the scenario where there are updates to the array as long as it doesn't become empty. If the array becomes empty and then gets repopulated with an identical id as previously it'll throw an error `There is already a source with this ID`

**Comment by abouroubi** [comment] 2020-06-16 16:52
Hi ! 
Any news on this ? 

Tried with the trackBy function, I don't have the errors anymore, but the layer is not rendered when I change my sourceData.

**Comment by dmytro-gokun** [comment] 2020-07-24 08:29
Guys, do you still have this issue in >= 4.8.0? It should have been fixed by that. Please let me know if it was not for someone.

**Closed** 2020-08-04 14:13 UTC
Labels: bug, need more info

**Comment by shanekwheeler** [comment] 2021-11-24 17:41
I have found another case where it appears the source is not removed.
https://stackblitz.com/edit/ngx-mapbox-gl-playground-sartya
