### ISSUE TITLE
TypeError: Object(…) is not a function

### ISSUE THREAD

**Issue by Ryanhustler420** [Wykks/ngx-mapbox-gl#169] opened 2019-07-16 09:38 UTC
I am using ngx-mapbox-gl on my Ionic 4 Project. the issue is if i use `<mgl-map></mgl-map>` it works just fine. but as soon as i use `<mgl-image></mgl-image>` and `<mgl-layout></mgl-layout>` than it throws an error

error message

```js
TypeError: Object(...) is not a function
    at SwitchMapSubscriber.project (http://localhost:8100/build/vendor.js:139738:85)
    at SwitchMapSubscriber._next (http://localhost:8100/build/vendor.js:126310:27)
    at SwitchMapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:35762:18)
    at AsyncSubject.Subject.next (http://localhost:8100/build/vendor.js:42338:25)
    at AsyncSubject.complete (http://localhost:8100/build/vendor.js:124181:35)
    at r.<anonymous> (http://localhost:8100/build/vendor.js:137687:29)
    at r.mt.fire (http://localhost:8100/build/vendor.js:126427:16160)
    at r._render (http://localhost:8100/build/vendor.js:126431:291581)
    at http://localhost:8100/build/vendor.js:126431:292690
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
```

> home.html

```html

<ion-header>
  <ion-navbar>
    <button ion-button menuToggle>
      <ion-icon name="menu"></ion-icon>
    </button>
    <ion-title>homePage</ion-title>
  </ion-navbar>
</ion-header>

<ion-content class="noScroll">
  <!-- [style]="'mapbox://styles/mapbox/streets-v9'" -->
  <mgl-map
    [style]="style"
    [zoom]="[zoom]"
    [touchZoomRotate]="true"
    [center]="[0,0]"
  >
    <mgl-image
      id="cat"
      url="https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cat_silhouette.svg/400px-Cat_silhouette.svg.png"
      (loaded)="imageLoaded = true"
    >
    </mgl-image>
    <mgl-layer
      *ngIf="imageLoaded"
      id="points"
      type="symbol"
      [source]="{
        type: 'geojson',
        data: {
          type: 'FeatureCollection',
          features: [
            {
              type: 'Feature',
              geometry: {
                type: 'Point',
                coordinates: [0,0]
              }
            }
          ]
        }
      }"
      [layout]="{'icon-image': 'cat', 'icon-size': 0.25}"
    >
    </mgl-layer>
  </mgl-map>
</ion-content>

```

> home.component.ts

```typescript

import {Component} from '@angular/core';
import {NavController} from 'ionic-angular';
import * as mapboxgl from 'mapbox-gl';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html',
})
export class HomePage {
  map: mapboxgl;
  style: string = 'mapbox://styles/mapbox/dark-v9';
  zoom: number = 15;
  cat;
  imageLoaded = false;
  counter = 0;

  constructor(public navCtrl: NavController) { }
}

```

> home.scss

```scss
mgl-map {
  height: 100%;
  width: 100%;
}

```

> package.json

```json

{
  "name": "map",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "~4.20.0",
    "@ionic-native/splash-screen": "~4.20.0",
    "@ionic-native/status-bar": "~4.20.0",
    "@ionic/storage": "2.2.0",
    "ionic-angular": "3.9.5",
    "ionicons": "3.0.0",
    "mapbox-gl": "^0.54.0",
    "ngx-mapbox-gl": "^3.3.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.2.2",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project"
}

```

i just want to put an image on my given latlng thats it.

**Comment by dmytro-gokun** [comment] 2019-10-18 07:18
@Ryanhustler420 Is this question still relevant? If yes, plz provide a minimal reproduction project (github reference, stackblitz etc) that one can actually build and run.

**Comment by dmytro-gokun** [comment] 2019-10-25 19:28
Closing this because of no reproduction information was provided. If you still have an issue/question, feel free to open a new issue and provide more details.

**Closed by dmytro-gokun** 2019-10-25 19:28 UTC
Labels: need more info
