### ISSUE TITLE
Module not found: Error: Can't resolve 'electron' in '...\@mapbox\mapbox-sdk\node_modules\got'

### ISSUE THREAD

**Issue by newcreativegamer** [Wykks/ngx-mapbox-gl#219] opened 2020-04-08 09:20 UTC
Hi,

My project is building fine using ng build, but when I use webpack to build the server-side production code I get the following error:
`ERROR in ./node_modules/@mapbox/mapbox-sdk/node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in '...\node_modules\@mapbox\mapbox-sdk\node_modules\got'
 @ ./node_modules/@mapbox/mapbox-sdk/node_modules/got/index.js 91:20-39
 @ ./node_modules/@mapbox/mapbox-sdk/lib/node/node-layer.js
 @ ./node_modules/@mapbox/mapbox-sdk/lib/node/node-client.js
 @ ./node_modules/@mapbox/mapbox-sdk/lib/client.js
 @ ./node_modules/@mapbox/mapbox-sdk/index.js
 @ ./node_modules/@mapbox/mapbox-gl-geocoder/lib/index.js
 @ ./node_modules/ngx-mapbox-gl/fesm5/ngx-mapbox-gl.js
 @ ./dist/server/main.js
 @ ./server.ts`

Any help would be much appreciate, I'm really stuck on this one.

Thanks,
Alan.

**Comment by newcreativegamer** [comment] 2020-04-08 09:56
It looks like this is caused by mapbox importing node modules that are not available in the browser (electron)?

**Comment by julien-deramond** [comment] 2020-04-27 20:38
I just had the same error by using webpack to build the server-side production code.
The build error can be fixed with a `npm i electron --save-dev` but I don't know for the moment if this is the right way of fixing the problem; indeed I still have problems running it after having it deployed.

**Comment by dmytro-gokun** [comment] 2020-07-25 19:35
@newcreativegamer Is this still a problem with the latests version (4.8.1)?

**Comment by prem6667** [comment] 2020-07-30 15:31
Yes, I am facing the same issue with version 4.8.1 
`ERROR in ./node_modules/@mapbox/mapbox-gl-geocoder/node_modules/@mapbox/mapbox-sdk/node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in 'D:\webui\node_modules\@mapbox\mapbox-gl-geocoder\node_modules\@mapbox\mapbox-sdk\node_modules\got'
`

**Comment by dmytro-gokun** [comment] 2020-07-30 16:13
@prem6667 Would you mind building a small reproduction? I'm not sure i will be able to help as i have no experience with server-side compilation, but let's see.

**Comment by tkutsuna** [comment] 2020-08-25 01:45
I have created a small repository where this issue occurs.

https://github.com/tkutsuna/mapbox-universal

And I succeeded in eliminating the window reference error using domino.

```
import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { existsSync, readFileSync } from 'fs';

import * as domino from 'domino';

const template = readFileSync(join(__dirname, '../browser', 'index.html')).toString();
const win = domino.createWindow(template);

(global as any).window = win;
window.URL = { createObjectURL() {} } as any;

class Blob {}
(global as any).Blob = Blob;

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';

// The Express app is exported so that it can be used by serverless Functions.
export function app() {
...
````

https://github.com/tkutsuna/mapbox-universal/tree/fix/window_is_not_defined

Is there any other good way?

**Comment by dmytro-gokun** [comment] 2020-09-23 10:00
@tkutsuna Sorry for the long delay. Question: are you sure this is caused by ```ngx-mapbox-gl``` and not by ```mapbox-gl-geocoder``` itself?

**Comment by tkutsuna** [comment] 2020-09-28 01:44
I think the `electron` and `window` issues are probably due to `mapbox-gl-geocoder`.

**Comment by dmytro-gokun** [comment] 2020-09-28 09:54
@tkutsuna If this issue is caused by ```mapbox-gl-geocoder``` than it has to be moved there :)

**Comment by tkutsuna** [comment] 2020-10-05 01:36
Since mapbox-gl is a library that only assumes operation on the client side, it seems impossible to guarantee operation on the server side.

On the other hand, ngx-mapbox-gl is an Angular library, and it is better to assume the operation on the server side.

It may be difficult to handle it with the code of ngx-mapbox-gl, but I think it would be better if there is an example of SSR in the documentation etc.

**Comment by dmytro-gokun** [comment] 2020-10-05 03:08
> On the other hand, ngx-mapbox-gl is an Angular library, and it is better to assume the operation on the server side.

Well, I'd argue ngx-mapbox-gl should not attempt to do better than the libs it depens on. This is way down the rabbit hole. IMO.

> It may be difficult to handle it with the code of ngx-mapbox-gl, but I think it would be better if there is an example of SSR in the documentation etc.

I absolutely agree. Would you volounteer for creating such an example that we can put in the documentation? Remember, it does not have to be perfect. Just something we (and other people) can iteratate on.

**Closed** 2020-12-07 12:21 UTC
Labels: help wanted, need more info, question
