### ISSUE TITLE
Demo site in edit mode is broken

### ISSUE THREAD

**Issue by mojesto** [Wykks/ngx-mapbox-gl#216] opened 2020-03-23 13:49 UTC
![broken-demo](https://user-images.githubusercontent.com/6073086/77323347-c8e2b000-6d1d-11ea-851b-cb0f33b9440e.png)

**Comment by timothyalcaide** [comment] 2020-07-09 14:12
https://github.com/Wykks/ngx-mapbox-gl/issues/227#issuecomment-656150507

**Comment by Wykks** [comment] 2020-07-09 15:56
Duplicate of #227

**Closed by Wykks** 2020-07-09 15:56 UTC
